
debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false


# transfer:
#   limit: 1000


---

spring:
  config:
    activate:
      on-profile:
      - test

transfer:
  limit: 200